

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_13_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_14_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_15_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_16_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_17_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_18_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_19_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_20_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.echo_stream_axis_sample_0_stream_axis_sample_0_bool_delay_buffer_21_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ4echoRN3hls6streamI11axis_sampleLi0EEES3_bE12delay_buffer_10_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ4echoRN3hls6streamI11axis_sampleLi0EEES3_bE12delay_buffer_11_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ4echoRN3hls6streamI11axis_sampleLi0EEES3_bE12delay_buffer_12_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ4echoRN3hls6streamI11axis_sampleLi0EEES3_bE12delay_buffer_13_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ4echoRN3hls6streamI11axis_sampleLi0EEES3_bE12delay_buffer_14_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ4echoRN3hls6streamI11axis_sampleLi0EEES3_bE12delay_buffer_15_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fadd_32ns_32ns_32_7_full_dsp_1_U1"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_4_max_dsp_1_U2"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sitofp_32ns_32_6_no_dsp_1_U3"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dadd_64ns_64ns_64_7_no_dsp_1_U4"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dmul_64ns_64ns_64_7_max_dsp_1_U5"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sitodp_32s_64_6_no_dsp_1_U6"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.srem_17ns_17ns_17_21_1_U7"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_33_4_24_1_1_U8"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_10s_34_1_1_U9"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_11s_35_1_1_U10"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_3_24_1_1_U11"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_11ns_35_1_1_U12"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_10ns_34_1_1_U13"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_12ns_36_1_1_U14"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_10s_34_1_1_U15"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_11ns_35_1_1_U16"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_12ns_36_1_1_U17"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_10ns_34_1_1_U18"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_10s_34_1_1_U19"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_24s_11s_35_1_1_U20"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_3_24_1_1_U21"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.temp1_fifo_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.temp2_fifo_U"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_r_U"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_r_U"}]}
set DependenceCheckSize 0
